config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'sauces#index' #---'pages#home'---

  resources :sauces, only: [:index, :show]
  resources :order_sauces, only: [:create]
  resources :orders, only: [:show, :create, :update, :edit] do
    resources :payments, only: :new
    resources :user, only: [:show]
  end
  resources :order_sauces, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  monetize :amount_cents
  has_many :order_sauces
  has_many :sauces, through: :order_sauce

  validates :name, presence: true, on: :update
  validates :address, presence: true, on: :update
  validates :email, presence: true, on: :update
  validates :number, presence: true, on: :update

  def total_price
    price = 0
    order_sauces.each do |os|
      price += os.sauce.price * os.quantity
    end
    price
  end
end

app/models/order_sauce.rb
class OrderSauce < ApplicationRecord
  belongs_to :sauce
  belongs_to :order
end

app/models/sauce.rb
class Sauce < ApplicationRecord
  monetize :price_cents
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

 has_many :orders

 def show
  @paid_orders = Order.where(:state == 'confirmed')
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/order_sauces_controller.rb
class OrderSaucesController < ApplicationController

  def create
    if params[:order_sauce][:order_id].blank?
      order = Order.create(state: 'pending')
      session[:order_id] = order.id
      order_sauce = OrderSauce.new(order_sauce_params)
      order_sauce.order = order
      order_sauce.save
    else
      OrderSauce.create(order_sauce_params)
    end
   redirect_back(fallback_location: order_sauces_path, notice: "succesfully added to cart")

  end

   def destroy
     @order_sauce = OrderSauce.find(params[:id])
     @order_sauce.destroy
     redirect_back(fallback_location: order_sauces_path, notice: "sauce deleted")
   end

  private

  def order_sauce_params
    params.require(:order_sauce).permit(:sauce_id, :quantity, :order_id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController


  def create
    sauce = Sauce.find(params[:sauce_id])
    order  = Order.create!(sauce: sauce, amount: sauce.price, state: 'pending')
    #order = Order.create!(order_params)
  end
  #redirect_back(fallback_location: order_path)
  

    def update
      
      @order = Order.find(params[:id])
      @order.update(order_params)
      redirect_to order_path(@order)
    end

   def edit
     @order = Order.find(params[:id])
   end



  def show
    @order = Order.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:name, :address, :email, :number, :sauce_id, :quantity, :order_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

def new
    @order = Order.where(state: 'pending').find(params[:order_id])
  end

end

app/controllers/sauces_controller.rb
class SaucesController < ApplicationController

  def index
    @sauces = Sauce.all
  end
  
  def show
    @sauce = Sauce.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BossiesChilli</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lora&display=swap" rel="stylesheet">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body data-turbolinks="false" >
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/order_sauces/edit.html.erb
<div class="chilli-banner">
  <div class="logo-small">
    <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609403856/bossieslogo_xoqibz.jpg" alt="Bossies" width="160px" class="logo-avatar">
  </div>
</div>
<div class="show-box">
 <h3> Your order </h3>
  <div class="show-box-sauce">
      <% @order.order_sauces.each do |os| %>
        <%= image_tag os.sauce.photo_url, width: '100%' %>
        <h3><%= os.sauce.name %></h3>
        <p> Quantity: <%= os.quantity %></p>
        <%= link_to "Delete?",
            order_sauce_path(os),
            class: "button-delete",
            method: :delete,
            remote: true,
            data: { confirm: "Are you sure?" } %>
      <% end %>
      <div class="back-button">
        <%= link_to 'add more sauces', sauces_path%>
      </div>
  </div>
  <div class="order-payment-details">
      <p>  R <%= @order.total_price %> ( + R 100 for shipping) </p>
      <h3> Total:  R <%= @order.total_price.to_i + 100%>
    <div class="purchase">
      <%= link_to 'Proceed to payment', new_order_payment_path(session[:order_id]), class: "checkout" %>
    </div>
  </div>
</div>

app/views/orders/create.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- Ensures optimal rendering on mobile devices. -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge" /> <!-- Optimal Internet Explorer compatibility -->
  </head>

  <body>
  <h1>hello</h1>
    <script src="https://www.paypal.com/sdk/js?client-id=AaeIBp0SFsrmoZB4J0JKhi2Mvx5HpXfRKSiwOAQF5Fz2K3_lsdRElWl6363Q05tw4V1XycpOEVzcG-WL"> // Replace YOUR_SB_CLIENT_ID with your sandbox client ID
    </script>

    <div id="paypal-button-container"></div>

    <!-- Add the checkout buttons, set up the order and approve the order -->
    <script>
      paypal.Buttons({
        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{
              amount: {
                value: '0.01'
              }
            }]
          });
        },
        onApprove: function(data, actions) {
          return actions.order.capture().then(function(details) {
            alert('Transaction completed by ' + details.payer.name.given_name);
          });
        }
      }).render('#paypal-button-container'); // Display payment options on your web page
    </script>
  </body>
</html>

app/views/orders/edit.html.erb
<div class="chilli-banner">
  <div class="logo-small">
    <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609403856/bossieslogo_xoqibz.jpg" alt="Bossies" width="160px" class="logo-avatar">
  </div>
</div>
<div class="show-box">
 <h3> Your Order </h3>
  <div class="show-box-sauce">
      <% @order.order_sauces.each do |os| %>
        <%= image_tag os.sauce.photo_url, width: '100%' %>
        <h3><%= os.sauce.name %></h3>
        <p> Quantity: <%= os.quantity %></p>
        <%= link_to "Delete?",
            order_sauce_path(os),
            class: "button-delete",
            method: :delete,
            remote: true,
            data: { confirm: "Are you sure?" } %>
      <% end %>
      <div class="back-button">
        <%= link_to 'add more sauces', sauces_path%>
      </div>
  </div>
  <div class="order-payment-details">
      <p>  R <%= @order.total_price %> ( + R 100 for shipping) </p>
      <h3> Total:  R <%= @order.total_price.to_i + 100%>
    <div class="purchase">
      <%= link_to 'Proceed to payment', new_order_payment_path(session[:order_id]), class: "checkout" %>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<div class="chilli-banner">
  <div class="logo-small">
    <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609403856/bossieslogo_xoqibz.jpg" alt="Bossies" width="160px" class="logo-avatar">
  </div>
</div>
<%= link_to 'home', sauces_path %>
<div class="show-box">
 <h3> Delivery details </h3>
  <div class="order-payment-details">
      <h5>Order #<%= @order.id %> <small><span class="badge badge-primary"><%= @order.state %></span></small></h5>
      <ul class="list-unstyled">
      </ul>
      <p>Estimated delivery in <strong>2 business days</strong></p>
      <p><b><%= @order.name %></b></p>
      <p><b><%= @order.address %></b></p>
      <p><b><%= @order.email %></b></p>
      <p><b><%= @order.number %></b></p>
      <h3>  R <%= @order.total_price %> + R 100 for shipping </h3>
      <h3> Total:  R <%= @order.total_price.to_i + 100%> </h3>
    <!--<div class="purchase">
      <%= link_to 'Purchase', new_order_payment_path(session[:order_id]), class: "checkout" %>
    </div> <!-->
    <p> Delivery details correct? If you're happy choose one of the payment options below. otherwise,</p>
    <%= link_to 'edit delivery details', new_order_payment_path(session[:order_id]) %>
  </div>
  <h3> Payment Methods </h3>
  <div class="paypal">
    <script src="https://www.paypal.com/sdk/js?client-id=AaeIBp0SFsrmoZB4J0JKhi2Mvx5HpXfRKSiwOAQF5Fz2K3_lsdRElWl6363Q05tw4V1XycpOEVzcG-WL"> // Replace YOUR_SB_CLIENT_ID with your sandbox client ID
    </script>

    <div id="paypal-button-container"></div>

    <!-- Add the checkout buttons, set up the order and approve the order -->
    <script>
      paypal.Buttons({
        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{
              amount: {
                value: <%= @order.total_price.to_i + 100 %>
              }
            }]
          });
        },
        onApprove: function(data, actions) {
          return actions.order.capture().then(function(details) {
            alert('Transaction completed by ' + details.payer.name.given_name);
          });
        }
      }).render('#paypal-button-container'); // Display payment options on your web page
    </script>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="logo">
   <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609403856/bossieslogo_xoqibz.jpg" alt="Bossies" width="200px">
  </div>
  <div class="container">
    <h1>"The best thing to come out of KZN since the Sharks!"</h1>
    <h4> Add some spice to your life and flavour to your soul!</h4>
  </div>
</div>
<body>
<div class="intro">
 <h3> Who are we? </h3>
  <h2> Headed up by the saltiest of sea dogs, and biggest fan of putting flame to vleis, Bossies Chilli co. is a collective of honest, down-to-earth farmers with a taste for delicious and wholesome food and even better sauces.</h2>
  <h2> Organically grown with love on our KZN Midlands farm, our African Birds eye Chillis are carefully blended with other locally-sourced ingredients to deliver the goodness that is our Bossie Chilli sauces. Whether to lather over braai meat, be the star of a cheese and snackboard platter, or simply on a good old fashioned roll or sarmie, Bossies Chilli co. is guaranteed to go down like a home-sick mole!</h2>
</div>
<div class="container2">
  <h3>Our Ama-zing selection!</h3>
  <div class="cards">
    <div class="card">
      <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609403301/chilli3_uxdgcy.jpg" alt>
      <h5>Sweet Chilli Green</h5>
      <p><b> Sweet, tangy and deliciously healthy </b><br>
       all the markings of the perfect companion for any dish</p>
       <a href="https://www.amandla.app" target="_blank"><button class="button"><bold>Let's go!</bold></button></a>
    </div>
    <div class="card">
       <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609403286/chilli2_dc6xdj.jpg" alt>
        <h5>Sweet Chilli</h5>
        <p><b> The good old faithful </b><br>
        perfect with just about anything but really shines with chees and snack platters!</p>
        <a href="https://www.amandla.app" target="_blank"><button class="button"><bold>Let's go!</bold></button></a>
    </div>
    <div class="card">
       <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609403265/chilli1_qsxjf9.jpg" alt>
        <h5>Jala-Tangy</h5>
        <p><b> Sharp and smooth </b><br>
        the perfect marinade for all things meaty!Lather em up and let the feast commence!</p>
        <a href="https://www.amandla.app" target="_blank"><button class="button"><bold>Let's go!</bold></button></a>
    </div>
  </div>
</div>
</body>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609403546/palmapose_j0wxho.jpg" class="center-block" alt="" height="500">
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609753261/alljars_smgznf.jpg" class="center-block" alt="" height="500">
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609403509/plattersmall_glfiqt.jpg" class="center-block" alt="" height="500">
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609403527/platterbig_dzgjuw.jpg" class="center-block" alt="" height="500">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
  <div class="contact">
      <a href="" target="_blank"><button class="button-contact"><bold>Contact us</bold></button></a>
  </div>
<div class="footer">
<h6> Connect with us on Social Media </h6>
  <ul class="list-inline">
           <li>
            <a href="https://www.facebook.com/ricky.schoeman.5" target="_blank">
                <i class="fab fa-facebook-f"></i>
            </a>
        </li>
        <li>
            <a href="https://www.instagram.com/bossies_chilli_company/" target="_blank">
                <i class="fab fa-instagram"></i>
            </a>
        </li>
       </ul>
</div>

app/views/payments/new.html.erb
<div class="chilli-banner">
  <div class="logo-small">
    <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609403856/bossieslogo_xoqibz.jpg" alt="Bossies" width="160px" class="logo-avatar">
  </div>
</div>
<div class="show-box">
 <h3> Delivery details </h3>
 <p> Who and where is the person that will receive this ama-zing delivery? </p>
 <!--<%= form_for(@order) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :address %>
        <%= f.text_field :address %>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <%= f.label :number %>
        <%= f.text_field :number %>
        <%= f.submit 'Submit', class: "button-contact" %>
      <% end %>-->
  <%= simple_form_for(@order) do |f| %>
  <%= f.input :name %>
  <p>Full Name*</p>
  <%= f.input :address %>
  <p>Delivery Address*</p>
  <%= f.input :email %>
  <p>Email*</p>
  <%= f.input :number %>
  <p>Contact number*</p>
  <%= f.submit 'Submit', class: "button-contact" %>
<% end %>
 <!--<h3> Payment </h3>
  <div class="paypal">
    <script src="https://www.paypal.com/sdk/js?client-id=AaeIBp0SFsrmoZB4J0JKhi2Mvx5HpXfRKSiwOAQF5Fz2K3_lsdRElWl6363Q05tw4V1XycpOEVzcG-WL"> // Replace YOUR_SB_CLIENT_ID with your sandbox client ID
    </script>

    <div id="paypal-button-container"></div>

   Add the checkout buttons, set up the order and approve the order
    <script>
      paypal.Buttons({
        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{
              amount: {
                value: <%= @order.total_price.to_i + 100 %>
              }
            }]
          });
        },
        onApprove: function(data, actions) {
          return actions.order.capture().then(function(details) {
            alert('Transaction completed by ' + details.payer.name.given_name);
          });
        }
      }).render('#paypal-button-container'); // Display payment options on your web page
    </script>
    </div>
    <div class="order-payment-details">
      <h5>Order #<%= @order.id %> <small><span class="badge badge-primary"><%= @order.state %></span></small></h5>
      <ul class="list-unstyled">
      </ul>
      <p>Estimated delivery in <strong>2 business days</strong></p>
      <h3>  R <%= @order.total_price %> + R 100 for shipping </h3>
      <h3> Total charged:  R <%= @order.total_price.to_i + 100%>
    </div>
  </div> -->
</div>

app/views/sauces/index.html.erb
<div class="banner">
  <div class="logo">
   <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609403856/bossieslogo_xoqibz.jpg" alt="Bossies" width="200px">
  </div>
  <div class="container">
    <h1>"The best thing to come out of KZN since the Sharks!"</h1>
  </div>
  <!--<%= link_to 'log in', new_user_session_path %>
  <%= link_to "Log out", destroy_user_session_path, method: :delete %>-->
  
</div>
<body>

<div class="intro">
 <h3> Who are we? </h3>
  <h2> Headed up by the saltiest of sea dogs, and biggest fan of putting flame to vleis, Bossies Chilli co. is a collective of honest, down-to-earth farmers with a taste for delicious and wholesome food and even better sauces.</h2>
  <h2> Organically grown with love on our KZN Midlands farm, our African Birds eye Chillis are carefully blended with other locally-sourced ingredients to deliver the goodness that is our Bossie Chilli sauces. Whether to lather over braai meat, be the star of a cheese and snackboard platter, or simply on a good old fashioned roll or sarmie, Bossies Chilli co. is guaranteed to go down like a home-sick mole!</h2>
</div>
<div class="container2">
  <h3>Our Ama-zing Selection!</h3>
  <div class="cards">
    <% @sauces.each do |sauce| %>
       <div class="card">
           <%= image_tag sauce.photo_url %>
              <h5>
                <%= sauce.name %>
              </h5>
              <p>
                <%= sauce.description %>
                <div class="action">
                <%= link_to "lets go!", sauce_path(sauce), class: "button" %>
                </div>
              </p>
        </div>
      <% end %>
  </div>
</div>
</body>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609403546/palmapose_j0wxho.jpg" class="center-block" alt="" height="500">
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609753261/alljars_smgznf.jpg" class="center-block" alt="" height="500">
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609403509/plattersmall_glfiqt.jpg" class="center-block" alt="" height="500">
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609403527/platterbig_dzgjuw.jpg" class="center-block" alt="" height="500">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
  <!--<div class="contact">
      <a href="" target="_blank"><button class="button-contact"><bold>Contact us</bold></button></a>
  </div>-->
<div class="footer">
<h6> Connect with us on Social Media </h6>
  <ul class="list-inline">
           <li>
            <a href="https://www.facebook.com/ricky.schoeman.5" target="_blank">
                <i class="fab fa-facebook-f"></i>
            </a>
        </li>
        <li>
            <a href="https://www.instagram.com/bossies_chilli_company/" target="_blank">
                <i class="fab fa-instagram"></i>
            </a>
        </li>
       </ul>
</div>

app/views/sauces/show.html.erb
<div class="chilli-banner">
  <div class="logo-small">
    <img src="https://res.cloudinary.com/rickyschoeman/image/upload/v1609403856/bossieslogo_xoqibz.jpg" alt="Bossies" width="160px" class="logo-avatar">
  </div>
</div>
<div class="show-box">
  <div class="show-box-sauce">
      <%= image_tag(@sauce.photo_url, width: '100%' ) %>
      <h4>
        <%= @sauce.name %>
      </h4>
      <p><bold>Ingredients:</bold> Birds eye chilli's, Vinegar, Apricots, Sugar, Garlic, Onions</p>
      <p>Organic and locally-sourced</p>
      <h3><%= humanized_money_with_symbol(@sauce.price) %> + shipping</h3>
    <div class="add-to-cart">
      <%= simple_form_for OrderSauce.new do |f| %>
        <%= f.input :sauce_id, input_html: { value: @sauce.id }, as: :hidden  %>
        <%= f.input :order_id, input_html: { value: session[:order_id] }, as: :hidden   %>
        <%= f.input :quantity, collection: (1..5)   %>
        <%= f.submit 'Add to Cart', class: "button-contact", remote: true %>
      <% end %>
       <div class="checkout-div">
        <% if session[:order_id] %>
        <%= link_to 'Edit/Confirm Order', edit_order_path(session[:order_id]), class: "checkout" %>
        <% end %>
       </div>
    </div>
     <div class="back-button">
      <%= link_to 'Add more sauces', sauces_path %>
     </div>
  </div>
</div>
 <div class="footer">
   <h6> Connect with us on Social Media </h6>
  <ul class="list-inline">
           <li>
            <a href="https://www.facebook.com/ricky.schoeman.5" target="_blank">
                <i class="fab fa-facebook-f"></i>
            </a>
        </li>
        <li>
            <a href="https://www.instagram.com/bossies_chilli_company/" target="_blank">
                <i class="fab fa-instagram"></i>
            </a>
        </li>
       </ul>
 </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>